version: "3.8"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:5173" # Map the container's port 5173 to the host
    volumes:
      - .:/app # Mount the current directory to the container
      - /app/node_modules # Avoid overwriting node_modules
    stdin_open: true
    tty: true
